# Pair pool and fixed-scale z-score training: local V2

Screen equities, commodity ETF/ETPs and other ETFs. Use the original `TS_implement.ipynb` / `TS_lib.py` **mean_square** scale and single-Z strategy. There is no rolling window in this version. Only `data/pair_pool.csv` is saved; no price cache or intermediate CSV is written. The old A/B/C version is preserved in GitHub tag `v1.0.0`; this V2 branch stays local.

In [1]:
from pathlib import Path
import logging
import pandas as pd
from IPython.display import display
from pair_pool import PairPoolConfig
from pair_training import SignalTrainingConfig, PairSignalTrainer

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

In [2]:
pool_config = PairPoolConfig(
    target_pairs=300,
    target_commodity_pairs=50,
    target_other_etf_pairs=50,
    min_market_cap=10_000_000_000,
    min_etf_assets=100_000_000,
    min_average_dollar_volume=20_000_000,
    output_file=Path("data/pair_pool.csv"),
)
training_config = SignalTrainingConfig(
    train_start="2022-01-01",
    train_end="2024-12-31",
    validation_start="2025-01-01",
    validation_end="2025-12-31",
    z_values=tuple(i / 4 for i in range(1, 15)),  # 0.25, 0.50, ..., 3.50
    exit_on_cross_mean=False,                    # Exit at Z / 2
    prevent_immediate_reentry=True,
    stop_loss=0.12,
    min_train_trades=5,
    min_validation_trades=2,
    long_amount=100_000,
)

## Method and assumptions

- **2022-2024:** screen pairs, fit Close OLS and residual AR(1), and estimate fixed `mu_e`, `theta` and `sigma_eq` with the original `mean_square` formula. There is no rolling window. Training performance is in-sample.
- Use `z=(spread-mu_e)/sigma_eq`. Test Z from 0.25 to 3.50; default exit is Z/2. Choose the highest training budget return, then Sharpe, with at least five completed trades.
- **2025:** validate once from flat positions with all training estimates and Z frozen. Require at least two validation trades and positive training/validation P&L and Sharpe. Keep failed rows with reasons. No 2026 prices are requested or used. Separate `refit_*` fields use data through 2025 for future deployment only.
- Close signals fill at the next common trading day's Open. High z shorts Y/longs X; low z reverses it. Exit on returning to or crossing the exit threshold. The 12% trade stop also fills next Open; gaps can exceed it. Suppress entry signals on a day that just executed an exit.
- Each pair has a fixed USD 200,000 budget, entry caps of USD 100,000 per leg, and integer shares held until exit. Returns equal P&L divided by that fixed budget. Flatten at each period's last Close; record `forced_exits` and `stop_exits`. Fees, borrow, financing and distribution cash flows remain zero.
- These are independent pair results, not one combined portfolio. Existing liquidity/EG/ADF filters remain; current metadata still cause survivorship/selection bias. Full formulas and accounting details are in [README.md](README.md).

In [3]:
trainer = PairSignalTrainer(training_config, pool_config=pool_config)
pair_pool = trainer.run()

display(pair_pool.groupby("pair_family").agg(
    candidates=("pair_id", "size"),
    validation_passed=("validation_passed", "sum"),
))
print("Saved:", pool_config.output_file)
print("Parameter training: 2022-2024 | Validation: 2025 | No 2026 prices")

INFO: Industry screens 10/145; 67 equity records

INFO: Industry screens 20/145; 177 equity records

INFO: Industry screens 30/145; 226 equity records

INFO: Industry screens 40/145; 290 equity records

INFO: Industry screens 50/145; 344 equity records

INFO: Industry screens 60/145; 394 equity records

INFO: Industry screens 70/145; 463 equity records

INFO: Industry screens 80/145; 519 equity records

INFO: Industry screens 90/145; 579 equity records

INFO: Industry screens 100/145; 608 equity records

INFO: Industry screens 110/145; 646 equity records

INFO: Industry screens 120/145; 712 equity records

INFO: Industry screens 130/145; 833 equity records

INFO: Industry screens 140/145; 875 equity records

INFO: Industry screens 145/145; 914 equity records

INFO: ETF metadata: 189/189 catalog entries returned USD ETF records

ERROR: $SKHY: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $SPCX: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
2 Failed downloads:

ERROR: ['SKHY', 'SPCX']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $SNDK: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
1 Failed download:

ERROR: ['SNDK']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $HONA: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
1 Failed download:

ERROR: ['HONA']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $MDLN: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $VYLR: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
2 Failed downloads:

ERROR: ['MDLN', 'VYLR']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $SUNB: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $VG: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $CRWV: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
3 Failed downloads:

ERROR: ['SUNB', 'VG', 'CRWV']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $BSP: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
1 Failed download:

ERROR: ['BSP']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $CBRS: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
1 Failed download:

ERROR: ['CBRS']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $Q: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
1 Failed download:

ERROR: ['Q']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $AMRZ: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $CRCL: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
2 Failed downloads:

ERROR: ['AMRZ', 'CRCL']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $ARXS: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
1 Failed download:

ERROR: ['ARXS']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $PS: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
1 Failed download:

ERROR: ['PS']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $FDXF: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
1 Failed download:

ERROR: ['FDXF']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $BMNR: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $JBS: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
2 Failed downloads:

ERROR: ['BMNR', 'JBS']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $FIG: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
1 Failed download:

ERROR: ['FIG']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $SAIL: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $MAIR: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $MICC: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
3 Failed downloads:

ERROR: ['SAIL', 'MAIR', 'MICC']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $RML: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $INIO: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $CHYM: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
3 Failed downloads:

ERROR: ['RML', 'INIO', 'CHYM']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $WSE: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
1 Failed download:

ERROR: ['WSE']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR: $PAYP: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

ERROR:
1 Failed download:

ERROR: ['PAYP']: Data doesn't exist for startDate = 1641013200, endDate = 1735707600

INFO: 1097 discovered assets; 876 liquid assets; 1151 correlated industry/related pairs

INFO: Accepted 25 total pairs; families={'other_etf': 19, 'commodity_etf': 6}; after 25 tests

INFO: Accepted 50 total pairs; families={'other_etf': 44, 'commodity_etf': 6}; after 60 tests

INFO: Accepted 75 total pairs; families={'other_etf': 50, 'commodity_etf': 6, 'equity': 19}; after 109 tests

INFO: Accepted 100 total pairs; families={'other_etf': 50, 'commodity_etf': 6, 'equity': 44}; after 157 tests

INFO: Accepted 125 total pairs; families={'other_etf': 50, 'commodity_etf': 6, 'equity': 69}; after 226 tests

INFO: Accepted 150 total pairs; families={'other_etf': 50, 'commodity_etf': 6, 'equity': 94}; after 296 tests

INFO: Accepted 175 total pairs; families={'other_etf': 50, 'commodity_etf': 6, 'equity': 119}; after 349 tests

INFO: Accepted 200 total pairs; families={'other_etf': 50, 'commodity_etf': 6, 'equity': 144}; after 465 tests

INFO: Accepted 225 total pairs; families={'other_etf': 50, 'commodity_etf': 6, 'equity': 169}; after 542 tests

INFO: Accepted 250 total pairs; families={'other_etf': 50, 'commodity_etf': 6, 'equity': 194}; after 658 tests

INFO: Accepted 275 total pairs; families={'other_etf': 50, 'commodity_etf': 6, 'equity': 219}; after 769 tests

INFO: Accepted 300 total pairs; families={'other_etf': 50, 'commodity_etf': 6, 'equity': 244}; after 886 tests

INFO: Accepted 325 total pairs; families={'other_etf': 50, 'commodity_etf': 6, 'equity': 269}; after 1024 tests

WARNING: commodity_etf: found 6 of target 50; thresholds were not relaxed.

WARNING: equity: found 277 of target 300; thresholds were not relaxed.

INFO: Signal training 25/333; validation passed=14

INFO: Signal training 50/333; validation passed=32

INFO: Signal training 75/333; validation passed=43

INFO: Signal training 100/333; validation passed=53

INFO: Signal training 125/333; validation passed=66

INFO: Signal training 150/333; validation passed=76

INFO: Signal training 175/333; validation passed=84

INFO: Signal training 200/333; validation passed=96

INFO: Signal training 225/333; validation passed=107

INFO: Signal training 250/333; validation passed=118

INFO: Signal training 275/333; validation passed=132

INFO: Signal training 300/333; validation passed=142

INFO: Signal training 325/333; validation passed=160

INFO: Signal training 333/333; validation passed=162

               candidates  validation_passed
pair_family
commodity_etf           6                  1
equity                277                128
other_etf              50                 33

Saved: data\pair_pool.csv
Parameter training: 2022-2024 | Validation: 2025 | No 2026 prices

In [4]:
columns = [
    "pair_id", "pair_family", "entry_z", "exit_z", "train_mu_e", "train_sigma_eq",
    "train_trades", "train_return_on_budget",
    "validation_trades", "validation_pnl", "validation_return_on_budget",
    "validation_sharpe", "validation_max_drawdown", "validation_passed", "validation_status",
]
display(pair_pool[columns].head(25).round(4))
ready_pairs = pair_pool.loc[pair_pool["validation_passed"]]
print("Pairs passing the validation rule:", len(ready_pairs))
display(ready_pairs[columns].head(20).round(4))
display(pair_pool["validation_status"].value_counts().to_frame("pairs"))

,pair_id,pair_family,entry_z,exit_z,train_mu_e,train_sigma_eq,train_trades,train_return_on_budget,validation_trades,validation_pnl,validation_return_on_budget,validation_sharpe,validation_max_drawdown,validation_passed,validation_status
0,TSCO__DKS,equity,1.75,0.875,-0.2034,0.4858,43,0.7272,23,79925.9332,0.3996,3.1688,-0.0493,True,passed
1,IOT__FICO,equity,0.75,0.375,-0.5302,0.8207,48,1.7291,19,123097.5310,0.6155,2.4477,-0.1196,True,passed
2,IJH__MDY,other_etf,2.25,1.125,-0.0001,0.0070,61,0.0198,20,2541.3909,0.0127,2.4376,-0.0010,True,passed
3,APO__AMP,equity,0.25,0.125,0.1735,1.4793,54,0.5949,16,43679.2039,0.2184,2.3767,-0.0292,True,passed
4,PSA__UDR,equity,2.75,1.375,0.6915,3.5756,29,0.5298,9,22666.1683,0.1133,2.2562,-0.0445,True,passed
5,CW__EMBJ,equity,1.50,0.750,3.0341,4.8012,24,0.7974,18,77546.1149,0.3877,2.1302,-0.1561,True,passed
6,IVE__IUSV,other_etf,1.25,0.625,0.0043,0.0592,49,0.0229,20,2333.7848,0.0117,1.9745,-0.0018,True,passed
7,VTI__ITOT,other_etf,0.50,0.250,-0.0017,0.0220,69,0.0161,26,1947.7948,0.0097,1.9269,-0.0019,True,passed
8,VICI__GLPI,equity,0.75,0.375,-0.0129,0.1668,51,0.3436,8,20477.6782,0.1024,1.8419,-0.0478,True,passed
9,SAP__CHKP,equity,1.00,0.500,-1.0290,4.4477,27,0.5550,11,45944.1614,0.2297,1.8199,-0.0449,True,passed
10,FIX__STRL,equity,1.00,0.500,-0.2484,3.9465,31,0.6276,17,66987.4877,0.3349,1.7297,-0.0728,True,passed
11,USB__KEY,equity,2.25,1.125,0.0446,0.4286,35,0.4637,10,22120.9035,0.1106,1.7277,-0.0231,True,passed
12,WEC__AEE,equity,1.75,0.875,-0.0912,0.4823,32,0.2272,11,13953.6592,0.0698,1.6628,-0.0158,True,passed
13,ILMN__RVTY,equity,3.50,1.750,-0.6096,6.3517,18,0.5548,6,33923.2254,0.1696,1.6084,-0.0743,True,passed
14,BLK__SEIC,equity,0.75,0.375,-8.1741,11.0071,38,0.4270,15,25270.3343,0.1264,1.5618,-0.0521,True,passed
15,SPGI__MCO,equity,1.75,0.875,-0.9965,2.0491,40,0.3179,12,15322.0506,0.0766,1.5528,-0.0235,True,passed
16,XLU__VPU,other_etf,3.50,1.750,0.0089,0.0273,25,0.0570,9,2662.6446,0.0133,1.5306,-0.0025,True,passed
17,SPGI__ICE,equity,2.75,1.375,-0.1414,3.3449,33,0.4580,8,23560.4381,0.1178,1.4819,-0.0515,True,passed
18,EPD__TRGP,equity,3.50,1.750,0.0751,0.1896,26,0.4213,8,19734.1907,0.0987,1.4746,-0.0282,True,passed
19,VOO__SPY,other_etf,0.25,0.125,-0.0004,0.0427,75,0.0334,38,1205.7444,0.0060,1.4517,-0.0017,True,passed
20,PTC__NTNX,equity,1.50,0.750,0.3897,2.0902,41,0.7757,13,50603.4188,0.2530,1.4410,-0.1141,True,passed
21,XLF__VFH,other_etf,1.00,0.500,0.0176,0.0587,34,0.0696,13,2879.7263,0.0144,1.4362,-0.0094,True,passed
22,CB__FNF,equity,0.25,0.125,2.5388,3.4625,53,0.8046,18,25745.2410,0.1287,1.4341,-0.0626,True,passed
23,TFC__KEY,equity,2.00,1.000,-0.0783,0.3516,34,0.4736,7,18795.9730,0.0940,1.4323,-0.0389,True,passed
24,MA__MUFG,equity,3.00,1.500,-0.3489,3.6704,36,0.7485,13,30982.9190,0.1549,1.4320,-0.0517,True,passed

Pairs passing the validation rule: 162

,pair_id,pair_family,entry_z,exit_z,train_mu_e,train_sigma_eq,train_trades,train_return_on_budget,validation_trades,validation_pnl,validation_return_on_budget,validation_sharpe,validation_max_drawdown,validation_passed,validation_status
0,TSCO__DKS,equity,1.75,0.875,-0.2034,0.4858,43,0.7272,23,79925.9332,0.3996,3.1688,-0.0493,True,passed
1,IOT__FICO,equity,0.75,0.375,-0.5302,0.8207,48,1.7291,19,123097.5310,0.6155,2.4477,-0.1196,True,passed
2,IJH__MDY,other_etf,2.25,1.125,-0.0001,0.0070,61,0.0198,20,2541.3909,0.0127,2.4376,-0.0010,True,passed
3,APO__AMP,equity,0.25,0.125,0.1735,1.4793,54,0.5949,16,43679.2039,0.2184,2.3767,-0.0292,True,passed
4,PSA__UDR,equity,2.75,1.375,0.6915,3.5756,29,0.5298,9,22666.1683,0.1133,2.2562,-0.0445,True,passed
5,CW__EMBJ,equity,1.50,0.750,3.0341,4.8012,24,0.7974,18,77546.1149,0.3877,2.1302,-0.1561,True,passed
6,IVE__IUSV,other_etf,1.25,0.625,0.0043,0.0592,49,0.0229,20,2333.7848,0.0117,1.9745,-0.0018,True,passed
7,VTI__ITOT,other_etf,0.50,0.250,-0.0017,0.0220,69,0.0161,26,1947.7948,0.0097,1.9269,-0.0019,True,passed
8,VICI__GLPI,equity,0.75,0.375,-0.0129,0.1668,51,0.3436,8,20477.6782,0.1024,1.8419,-0.0478,True,passed
9,SAP__CHKP,equity,1.00,0.500,-1.0290,4.4477,27,0.5550,11,45944.1614,0.2297,1.8199,-0.0449,True,passed
10,FIX__STRL,equity,1.00,0.500,-0.2484,3.9465,31,0.6276,17,66987.4877,0.3349,1.7297,-0.0728,True,passed
11,USB__KEY,equity,2.25,1.125,0.0446,0.4286,35,0.4637,10,22120.9035,0.1106,1.7277,-0.0231,True,passed
12,WEC__AEE,equity,1.75,0.875,-0.0912,0.4823,32,0.2272,11,13953.6592,0.0698,1.6628,-0.0158,True,passed
13,ILMN__RVTY,equity,3.50,1.750,-0.6096,6.3517,18,0.5548,6,33923.2254,0.1696,1.6084,-0.0743,True,passed
14,BLK__SEIC,equity,0.75,0.375,-8.1741,11.0071,38,0.4270,15,25270.3343,0.1264,1.5618,-0.0521,True,passed
15,SPGI__MCO,equity,1.75,0.875,-0.9965,2.0491,40,0.3179,12,15322.0506,0.0766,1.5528,-0.0235,True,passed
16,XLU__VPU,other_etf,3.50,1.750,0.0089,0.0273,25,0.0570,9,2662.6446,0.0133,1.5306,-0.0025,True,passed
17,SPGI__ICE,equity,2.75,1.375,-0.1414,3.3449,33,0.4580,8,23560.4381,0.1178,1.4819,-0.0515,True,passed
18,EPD__TRGP,equity,3.50,1.750,0.0751,0.1896,26,0.4213,8,19734.1907,0.0987,1.4746,-0.0282,True,passed
19,VOO__SPY,other_etf,0.25,0.125,-0.0004,0.0427,75,0.0334,38,1205.7444,0.0060,1.4517,-0.0017,True,passed

                           pairs
validation_status
passed                       162
validation_not_profitable    158
too_few_validation_trades      9
data_or_model_error            3
training_not_profitable        1

## ETF coverage

The catalog covers bullion, energy, agriculture, industrial metals, broad commodities, equity indices/sectors and bonds. A category can have zero accepted pairs. Same-index/physical-metal `tracking_pair` candidates are explicitly flagged; they do not establish a trading edge or tax eligibility. Selection targets are not filled by weakening thresholds.

In [5]:
with pd.option_context("display.max_rows", None):
    display(trainer.pool_result["etf_coverage"])
print("Source events:", trainer.pool_result["events"][:10])

,pair_family,exposure_group,catalog_funds,metadata_funds,size_eligible_funds,formation_eligible_funds,accepted_pairs_involving_group
0,commodity_etf,agriculture_basket_futures,3,3,2,0,0
1,commodity_etf,battery_metals_futures,1,1,0,0,0
2,commodity_etf,broad_commodity_futures,12,12,12,1,0
3,commodity_etf,copper_futures,1,1,1,0,0
4,commodity_etf,corn_futures,1,1,1,0,0
5,commodity_etf,crude_oil_futures,4,4,3,0,0
6,commodity_etf,energy_basket_futures,1,1,1,0,0
7,commodity_etf,gasoline_futures,1,1,1,0,0
8,commodity_etf,gold_physical,8,8,8,8,5
9,commodity_etf,industrial_metals_futures,1,1,1,0,0
10,commodity_etf,natural_gas_futures,2,2,1,1,0
11,commodity_etf,palladium_physical,1,1,1,0,0
12,commodity_etf,platinum_physical,2,2,2,0,0
13,commodity_etf,precious_basket_physical,1,1,1,0,0
14,commodity_etf,precious_futures,1,1,1,0,0
15,commodity_etf,silver_physical,2,2,2,2,1
16,commodity_etf,soybean_futures,1,1,0,0,0
17,commodity_etf,sugar_futures,1,1,0,0,0
18,commodity_etf,wheat_futures,1,1,1,0,0
19,other_etf,aggregate_bond,4,4,4,0,0
20,other_etf,cash_treasury,3,3,3,0,0
21,other_etf,communication_equity,4,4,4,1,0
22,other_etf,consumer_discretionary_equity,4,4,4,1,0
23,other_etf,consumer_staples_equity,4,4,4,1,0
24,other_etf,dividend_equity,5,5,5,5,0
25,other_etf,emerging_equity,4,4,4,3,1
26,other_etf,emerging_usd_bond,3,3,3,0,0
27,other_etf,energy_equity,4,4,4,0,0
28,other_etf,financial_equity,4,4,4,3,1
29,other_etf,gold_miner_equity,5,5,5,2,0
30,other_etf,healthcare_equity,4,4,4,2,1
31,other_etf,high_yield_credit,4,4,4,0,0
32,other_etf,industrial_equity,4,4,4,1,0
33,other_etf,intermediate_treasury,4,4,4,0,0
34,other_etf,international_developed,4,4,4,4,5
35,other_etf,international_hedged_bond,2,2,2,0,0
36,other_etf,investment_grade_credit,5,5,5,0,0
37,other_etf,long_treasury,3,3,3,1,1
38,other_etf,materials_equity,4,4,4,1,0
39,other_etf,municipal_bond,3,3,3,0,0
40,other_etf,nasdaq100,2,2,2,2,1
41,other_etf,real_estate_equity,4,4,4,0,0
42,other_etf,resource_equity,4,4,4,1,0
43,other_etf,semiconductor_equity,3,3,3,2,0
44,other_etf,short_investment_grade_credit,3,3,3,0,0
45,other_etf,short_tips_bond,2,2,2,2,0
46,other_etf,short_treasury,4,4,4,0,0
47,other_etf,strips_treasury,2,2,2,2,1
48,other_etf,technology_equity,4,4,4,4,1
49,other_etf,tips_bond,2,2,2,1,0
50,other_etf,us_growth,5,5,5,5,4
51,other_etf,us_large_cap,2,2,2,2,11
52,other_etf,us_mid_cap,4,4,4,4,2
53,other_etf,us_small_cap,5,5,5,5,3
54,other_etf,us_sp500,4,4,4,4,15
55,other_etf,us_total_market,4,4,4,4,15
56,other_etf,us_value,5,5,5,5,3
57,other_etf,utilities_equity,4,4,4,2,1

Source events: ['missing_history SPCX: No closing prices', 'missing_history SKHY: No closing prices', 'missing_history SNDK: No closing prices', 'missing_history HONA: No closing prices', 'missing_history VYLR: No closing prices', 'missing_history MDLN: No closing prices', 'missing_history SUNB: No closing prices', 'missing_history VG: No closing prices', 'missing_history CRWV: No closing prices', 'missing_history BSP: No closing prices']